name: Terraform Backend Apply

on:
  workflow_dispatch:

jobs:
  apply-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init (Backend)
        run: |
          cd terraform/backend
          terraform init

      - name: Terraform Plan (Backend)
        run: |
          cd terraform/backend
          terraform plan

      - name: Terraform Apply (Backend)
        run: |
          cd terraform/backend
          terraform apply -auto-approve
