name: Terraform Apply All

on:
  workflow_dispatch:

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Apply - Backend
        run: |
          cd terraform/Backend
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - ECR
        run: |
          cd terraform/ECR
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - RDS
        run: |
          cd terraform/RDS
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - LOG
        run: |
          cd terraform/LOG
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply - EKS
        run: |
          cd terraform/EKS
          terraform init
          terraform apply -auto-approve
