name: Terraform LOG Apply

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ✅ Install Terraform
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # ✅ Configure AWS
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd terraform/LOG
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/LOG
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform/LOG
          terraform apply -auto-approve
